
#Increase the number to generate more structures. Set 0 to not generate.
["Configs for Chefs Delight"]
	#Plains Chef House Config - Default = 5
	"Plains Chef House" = 5
	#Plains Cook House Config - Default = 2
	"Plains Cook House" = 2
	#Taiga Chef House Config - Default = 4
	"Taiga Chef House" = 4
	#Taiga Cook House Config - Default = 3
	"Taiga Cook House" = 3
	#Desert Chef House Config - Default = 5
	"Desert Chef House" = 5
	#Desert Cook House Config - Default = 3
	"Desert Cook House" = 3
	#Savanna Chef House Config - Default = 6
	"Savanna Chef House" = 6
	#Savanna Cook House Config - Default = 2
	"Savanna Cook House" = 2
	#Snowy Chef House Config - Default = 4
	"Snowy Chef House" = 4
	#Snowy Cook House Config - Default = 1
	"Snowy Cook House" = 1

