
["Armor Effects"]

	["Armor Effects".eclipse_soldier]
		effects = ["minecraft:strength,259,0", "minecraft:resistance,259,0"]

	["Armor Effects".dragonslayer]
		effects = ["minecraft:strength,259,0", "minecraft:fire_resistance,259,0"]

	["Armor Effects".hero]
		effects = ["minecraft:regeneration,259,0"]

	["Armor Effects".golden_horns]
		effects = ["minecraft:haste,259,1"]

	["Armor Effects".thief]
		effects = ["minecraft:jump_boost,259,0"]

	["Armor Effects".wandering_wizard]
		effects = ["minecraft:water_breathing,259,0", "minecraft:night_vision,259,0", "minecraft:fire_resistance,259,0"]

	["Armor Effects".chess_board_knight]
		effects = ["minecraft:haste,259,0", "minecraft:regeneration,259,0", "minecraft:strength,259,0"]

	["Armor Effects".dark_lord]
		effects = ["minecraft:strength,259,0", "minecraft:night_vision,259,0", "minecraft:fire_resistance,259,0"]

	["Armor Effects".sunset_wings]
		effects = ["minecraft:jump_boost,259,0"]

	["Armor Effects".fog_guard]
		effects = ["minecraft:fire_resistance,259,0", "minecraft:resistance,259,0"]

	["Armor Effects".dark_cover]
		effects = ["minecraft:regeneration,259,0", "minecraft:strength,259,0"]

	["Armor Effects".spark_of_dawn]
		effects = ["minecraft:night_vision,259,0", "minecraft:fire_resistance,259,0"]

	["Armor Effects".golden_execution]
		effects = ["minecraft:strength,259,0"]

	["Armor Effects".forgotten_trace]
		effects = ["minecraft:haste,259,0", "minecraft:regeneration,259,0"]

	["Armor Effects".redeemer]
		effects = ["minecraft:strength,259,0", "minecraft:fire_resistance,259,0"]

	["Armor Effects".twinned]
		effects = ["minecraft:regeneration,259,0", "minecraft:haste,259,1"]

	["Armor Effects".gilded_hunt]
		effects = ["minecraft:jump_boost,259,0", "minecraft:strength,259,0"]

	["Armor Effects".lady_maria]
		effects = ["minecraft:strength,259,0", "minecraft:regeneration,259,0"]

	["Armor Effects".crucible_knight]
		effects = ["minecraft:fire_resistance,259,0", "minecraft:regeneration,259,0"]

	["Armor Effects".evening_ghost]
		effects = ["minecraft:regeneration,259,0", "minecraft:night_vision,259,0"]

	["Armor Effects".ronin]
		effects = ["minecraft:jump_boost,259,0"]

	["Armor Effects".malenia]
		effects = ["minecraft:regeneration,259,0"]

	["Armor Effects".old_knight]
		effects = ["minecraft:strength,259,0", "minecraft:resistance,259,0"]

	["Armor Effects".silver_knight]
		effects = ["minecraft:luck,259,0", "minecraft:strength,259,0"]

	["Armor Effects".dead_gladiator]
		effects = ["minecraft:regeneration,259,0"]

	["Armor Effects".flesh_of_the_feaster]
		effects = ["minecraft:resistance,259,0"]

	["Armor Effects".wind_worshipper]
		effects = ["minecraft:jump_boost,259,0"]

	["Armor Effects".grave_sentinel]
		effects = ["minecraft:strength,259,0", "minecraft:fire_resistance,259,0"]

	["Armor Effects".ornstein]
		effects = ["minecraft:regeneration,259,0", "minecraft:resistance,259,0"]

