
#Game settings
[settings]
	#Are tea bushes bonemealable?
	enableBoneMealTeaBush = false
	#Are coffee bushes bonemealable?
	enableBoneMealCoffeeBush = false
	#Chance of generating clusters. Smaller value = more frequent.
	#Range: > 0
	teaBushChance = 100
	#Chance of generating clusters. Smaller value = more frequent.
	#Range: > 0
	coffeeBushChance = 100

