
["Biome weights"]
	#Spawn weight of the Hickory Forest biome (def: 3)
	hickory_forest_weight = 3
	#Spawn weight of the Glowing Hickory Forest biome (def: 1)
	glowing_hickory_forest_weight = 1
	#Spawn weight of the Vibrion Hive biome (def: 4)
	vibrion_hive_weight = 4

["Hickory colour noise"]
	#Seed of the noise used to generate Hickory colour placements (def: 20080424)
	hickory_colour_noise_seed = 20080424
	#Scale of the noise used to generate Hickory colour placements (higher -> smaller patches) (def: 0.01)
	hickory_colour_noise_scale = 0.01

["Enable/disable features"]
	#Enable/disable the glowing tick of glowing blocks in the Glowing Hickory Forest, making them not change their light levels anymore (true = enable, false = disable) (def: true)
	glowing_hickory_tick = true

